### ISSUE TITLE
Removing the name of the person we cannot reach from wiki Sidebar

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#10]
Should we remove it?

**Comment by aycignl** [comment]
I agree with this opinion. 
If he comes, we will rearrange wiki sidebar.
Best.

**Comment by murat0431** [comment]
I agree with the opinion too.

**Comment by karacasoft** [comment]
Then I'll remove the name and close this issue for now. Feel free to re-open whenever you object to my decision. 😀
