### ISSUE TITLE
Start building Android

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#103]
## About

The API is ready to be used now. We may start building Android at once. 

Requirements:
* An android application project shall be initiated on the repository.
* The application shall be able to show the groups and their details.

Optional:
* Add login/register
* Add group creation
* Add post creation

**Comment by gauravrai1** [comment]
In which directory should I start?

**Comment by karacasoft** [comment]
Well, this is a course project. I don't know what professor @uskudarli thinks about getting help from outside of our group.

To answer the question, we might create a directory named `android` and put the project there.
