### ISSUE TITLE
Milestone report

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#108]
## About

Milestone report should be ready after the presentation.

**Comment by smddzcy** [comment]
What is our current status on this one?
@iremUlutas @norubai Will you be able to finish it tomorrow before ~4 pm? I guess the actual deadline is 5 pm but we'll probably need 1 hour for final touches & reviews.

**Comment by esra-aydemir** [comment]
The milestone report is written and merged in github.
