### ISSUE TITLE
Template for draft wiki pages?

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#11]
Should we put some text to define the wiki pages that are in draft stage?

**Comment by aycignl** [comment]
Actually, we can add a line at the top of the wiki page like 'this is a draft version', or 'to be updated'.
Best.

**Comment by karacasoft** [comment]
True. We can also create a box that includes the text "this is a draft version", like Wikipedia. Except no heavy styling(coloring, border style,...) is required, just a box, and the text.

**Comment by karacasoft** [comment]
Is this piece of code OK to put on every draft page?

`> **This page is currently a draft. We will improve it soon.**`

**Comment by karacasoft** [comment]
Although there's no real feedback here, it seems this thing is kinda accepted so I'm closing this issue for now.
