### ISSUE TITLE
Unofficial Milestone should be set

### ISSUE THREAD

**Issue by iremUlutas** [bounswe/bounswe2017group5#116]
## About

We need to determine an unofficial milestone and requirements for it before the second milestone/presentation which is on 30.11.2017.

## To-do

- [x] Set the milestone date.
- [x] Set the requirements until this date.

**Comment by smddzcy** [comment]
It'd be better if we create these milestones on GitHub as well. See: https://github.com/bounswe/bounswe2017group5/milestones
