### ISSUE TITLE
Implement the signup endpoint in our API

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#117]
## About

* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Meeting-18-07.11.2017

As discussed in our last meeting on 7th of November, we should implement the sign up endpoint in our API.

**Comment by smddzcy** [comment]
@triforce930 AFAIK this will be implemented for our Android application, right? Because we already have a working sign up page, so I'm assuming (I haven't checked yet) we have sign up implemented for our frontend 😄

**Comment by karacasoft** [comment]
Yes. Indeed, we need this for the application.

**Comment by smddzcy** [comment]
@iremUlutas any progress?
