### ISSUE TITLE
Create importance labels

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#119]
## About

We should create importance labels to label our issues/PRs according to their importance and have the most important tasks always on the front.

**Comment by smddzcy** [comment]
Done, our new labels:

`importance: trivial`: `#f9d0c4`
`importance: minor`: `#e99695`
`importance: major`: `#D84341`
`importance: urgent`: `#b60205`

@triforce930 please check their color. We may color them differently.

**Comment by karacasoft** [comment]
I liked the colors, no change required.

**Comment by karacasoft** [comment]
Closing this...
