### ISSUE TITLE
Should we still consider Requirements page a draft?

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#13]
We have added our current list of requirements now to GitHub wiki. Shall we remove the "draft" header of the page?

**Comment by aycignl** [comment]
I think this version of Requirements page seems to be ok.

**Comment by karacasoft** [comment]
So it's not a draft anymore, then?

**Comment by aycignl** [comment]
Actually, yes. Now, it is not a draft. 
If TAs give feedback, we will edit Requirements page again.
Best.

**Comment by karacasoft** [comment]
Allright :+1:
