### ISSUE TITLE
Group creation should be allowed with empty members list

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#133]
## About

Group member list should not be edited through API. Adding 'read_only' to the serializer field should work.

## Visuals

![image](https://user-images.githubusercontent.com/5247569/32885341-48697e34-cace-11e7-8670-acef386a655c.png)

**Comment by Morgazipa** [comment]
Perhaps the title is a bit misleading. Also, should the same apply for moderators field?

**Comment by karacasoft** [comment]
Changed the title [x] :+1:

Moderators field came after I found the issue. Yes, the same should be applied to the moderators field.
