### ISSUE TITLE
Joined groups list does not refresh after joining/leaving a group

### ISSUE THREAD

**Issue by Morgazipa** [bounswe/bounswe2017group5#148]
## About

* **Related Issues:** #130 

The joined groups list on the left side does not refresh after joining/leaving a group in a group detail page.

## Visuals

Group page after a user has a joined a new group
![screenshot-2017-11-25 create a new group - interestr](https://user-images.githubusercontent.com/25618553/33231286-fca36562-d1fa-11e7-9e7a-5088cb3f7a7b.png)

## To-do

Even though I very much like and appreciate the work done with Join/Leave button,  I think we should simply refresh the page after joining/leaving just not to bother ourselves with issues described here and #130.

**Comment by yfenes** [comment]
It's done.
