### ISSUE TITLE
Editing the project requirements until 25.02.2017

### ISSUE THREAD

**Issue by iremUlutas** [bounswe/bounswe2017group5#15]
We need to review the projects requirements documentation according to the feedback we received from our customer.

**Comment by buzem** [comment]
OK, I will look at it now.

**Comment by karacasoft** [comment]
Why is this not resolved yet?

**Comment by iremUlutas** [comment]
I've actually assigned myself to it and finished doing it. just forgot to resolve. Sorry, my bad.
