### ISSUE TITLE
Registering with an already used email address should not be allowed

### ISSUE THREAD

**Issue by Morgazipa** [bounswe/bounswe2017group5#150]
## About

As things stand, a new user can register with an already used email address. Considering that we allow sign in with email as an option, this should really be forbidden.

## Steps to reproduce the issue

1. First try to register with username "xxx" and email "xxx@example.com"
2. Log out
3. Try to register with  username "xxx2" and email "xxx@example.com"

Instead of being correctly confronted with an error message, the user is successfully logged in.

**Comment by murat0431** [comment]
Yes you are right. We should not allow this to happen. Tonight I will try to find a solution for the issue.

**Comment by murat0431** [comment]
@Morgazipa  I found a solution and I changed the code in the branch "murat_test" Can you check my latest commit about unique email and let me know if there is a problem about it? Also test it with same mail :)

**Comment by Morgazipa** [comment]
Since the branch was merged, I am closing this.(This issue is no longer relevant.)
