### ISSUE TITLE
Some Tests are not compiling

### ISSUE THREAD

**Issue by oal55** [bounswe/bounswe2017group5#160]
## About

Following tests aren't compiling let alone failing
- Comment Tests
  * test_create_comment
  * test_delete_comment
  * test_existing_comment
  * test_non_existing_comment
- Post Tests
  * test_existing_post
  * test_non_existing_post

One reason could be, post models have no such field as 'text'. But changing that alone doesn't fix the problems.

**Comment by Morgazipa** [comment]
This is hopefully fixed by #183.
