### ISSUE TITLE
Web UI for recommendations

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#175]
## About

* **Related Issues:** #176 
* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Milestone-2-Report

According to our roadmap in our last milestone report, we should implement the web UI for recommendations.

**Comment by smddzcy** [comment]
Since it's one of the first items in our roadmap, I put major importance to this one.

**Comment by ThoAppelsin** [comment]
I'm on a tight schedule. I have an exam tomorrow, and the next day, a deadline for a homework that I probably won't be able to finish entirely.

I will start doing it on Thursday, unless someone else on the frontend team (or anywhere else) thinks that it will be too late then.

**Comment by smddzcy** [comment]
@ThoAppelsin I can look at it tomorrow, I guess. Assigning myself 👍
