### ISSUE TITLE
Android UI for recommendations

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#177]
## About

* **Related Issues:** #176 
* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Milestone-2-Report

According to our roadmap in our last milestone report, we should implement the Android UI for recommendations.

**Comment by karacasoft** [comment]
I'm working on this :+1:

**Comment by karacasoft** [comment]
How does this look?

![feed_and_recommendations](https://user-images.githubusercontent.com/5247569/33939449-467c59f8-e01c-11e7-8bef-d2cfe1cd7878.gif)

**Comment by smddzcy** [comment]
Perfect 👌 Btw we also need the group recommendations UI.

**Comment by karacasoft** [comment]
This one is done...
