### ISSUE TITLE
Group moderation features

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#179]
## About

* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Milestone-2-Report

According to our roadmap in our last milestone report, we should implement group moderation features such as adding a user to a group, warning a user, banning a user from a group, reporting a user and so on.

## To-do

- [ ] Backend
  - [ ] Warning a user
  - [x] Banning a user
  - [ ] Reporting a user
- [ ] Web UI for all the features above
- [ ] Android UI for all the features above

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group5 Please assign yourselves to this and other open issues otherwise we'll need to randomly assign people 😄

**Comment by karacasoft** [comment]
You may auto-assign me to anything that is tagged with android :V

**Comment by oal55** [comment]
I'd like to help this one too, but we need to do a bit of discussion before we start.

**Comment by smddzcy** [comment]
@triforce930 @norubai Please make some progress, or show us if you've already made 😄 I'll handle its backend/frontend tomorrow if no one else does.
