### ISSUE TITLE
Implementing backend for advanced search queries

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#180]
## About

* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Milestone-2-Report

We should be able to handle advanced search queries, such as;
- Complex queries on posts, e.g. _“Give me the responses on this group which has
the data template X, where the response to the question Y is greater than Z.”_
- Complex queries on groups and users, e.g. _“Give me the users who joined more
than 5 groups and have at least 3 groups in common with me.”_

**Comment by smddzcy** [comment]
We should discuss the implementation details for this one.

**Comment by Morgazipa** [comment]
I was thinking that we only had to support the first type of queries, i.e. template based search.

**Comment by smddzcy** [comment]
It's done for now 👍
