### ISSUE TITLE
Preparing a user manual

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#193]
## About

As per our final deliverables, we need to provide a user manual with our software that instructs how users can use our system.

**Comment by iremUlutas** [comment]
If possible, a sample displaying how it should look like would be delightful.

**Comment by smddzcy** [comment]
No sample is provided to us, but there should be thousands (if not millions) of them online. Please Google it 😄 (e.g. “user manual template” or “user manual example”)

**Comment by iremUlutas** [comment]
Done and uploaded.
