### ISSUE TITLE
Cannot create posts with default template

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2017group5#202]
## About

I don't know when this issue has emerged, but I cannot seem to share posts with the default template, the one with just the "Text" field.

I have checked if I can share on a previous version, and I can. I think we can easily pin-point the cause of the issue by going back in time. Not urgent, so I won't do it asap.

**Comment by smddzcy** [comment]
Fixed with cfd296869b7c8b86e43ba91f46f9177225dd78db.
