### ISSUE TITLE
edit Search a group page in Web mockup

### ISSUE THREAD

**Issue by aycignl** [bounswe/bounswe2017group5#21]
need to edit this part in Web mockup: Search a group ---> Search facility may also use tags.
Please, close this issue when you fix it.

**Comment by karacasoft** [comment]
The search system uses tags implicitly. We don't have to show tags of the groups on Search bar. It'll create too much distraction for the user. But we can add a search in tag functionality. But that's not the case of this issue which I'm just closing now...
