### ISSUE TITLE
edit Profile page in Web mockup

### ISSUE THREAD

**Issue by aycignl** [bounswe/bounswe2017group5#23]
need to edit this part: Profile page ---> We see Mahmut's account and his profile page. But Follow button is active, I understand from its color. Please use corresponding data and scenario.
Please, close this issue when you fix it.

**Comment by karacasoft** [comment]
This is a misconception. That profile page is not of Mahmut. I actually thought about it while designing the page, (I was like "we are looking at Mahmut's profile page as Mahmut and he can follow himself. There must be something wrong :V") and just changed the profile name.

We can think of it as another account created by a person that looks really (I mean REALLY) similar to Mahmut and very interestingly shares the same hobbies and interests with Mahmut.

Anyway :V I fixed the issue by changing the title of the image.
This one is closed...
