### ISSUE TITLE
About issue naming...

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#26]
We should use more specific issue titles to make them more understandable when it is called. That is actually one of my ideas about this. We can create a rulebook of issue naming here with your comments.

Join in! 😀

**Comment by karacasoft** [comment]
1) Issues should be ~~named~~ titled a little bit specific about the issue itself, to make them understandable at first sight.

**Comment by aycignl** [comment]
You're right! 
2. Issue ~~names~~ titles should start a verb, be short, include understandable statements.
**Exception:** Issues with _question_ tag may ignore this rule.

**Comment by karacasoft** [comment]
3. Issue titles should not be longer than 100(debatable) characters.

**Comment by yfenes** [comment]
I think we are all clear about this issue now :)
"Dağılalım" as in meetings :)

**Comment by karacasoft** [comment]
Reopening this to say that I find the second rule to be too restrictive and I request it to be completely removed.

**Comment by karacasoft** [comment]
I take this silence as a sign of acceptance and close this issue for now.
