### ISSUE TITLE
More mock-ups?

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#27]
What can we add to our current set of mock-ups? Or what could we improve in our UI/UX? (Considering the mock-ups, of course)

**Comment by EgemenKaplan** [comment]
We can add a mock-up for the report system: one for regular users to report ill-behaviour and one for moderators to handle the reports they receive.

**Comment by karacasoft** [comment]
Aaah! An admin/moderator panel! Sounds interesting. But needs a lot of work. Especially when we just created the class and sequence diagrams. Might want to create a separate issue just for that.

Other than that, we also need a new name for our project. Check #31 pls.
