### ISSUE TITLE
Use case diagram must be revised.

### ISSUE THREAD

**Issue by yfenes** [bounswe/bounswe2017group5#29]
Use case diagram must be revised until 14.03.2017.
Specifically delete function and user types must be revised.

**Comment by karacasoft** [comment]
Let's just remove the 2nd rule of #26 :V

**Comment by karacasoft** [comment]
Why is this still open?

**Comment by karacasoft** [comment]
Was this forgotten to close or the job specified was never done? @yfenes

**Comment by yfenes** [comment]
It was forgotten to close. Sorry about that. The job was done the day I opened this issue.

Actually forgetting issues is an issue for me :)
