### ISSUE TITLE
Introduce project

### ISSUE THREAD

**Issue by aycignl** [bounswe/bounswe2017group5#30]
Can we introduce our project on the home page of our repository?
Best.

**Comment by karacasoft** [comment]
Wonderful idea! Who's willing to do it? :V

**Comment by aycignl** [comment]
I think I can do it 👍  I will update...

**Comment by karacasoft** [comment]
I'm looking for it... 👀

**Comment by aycignl** [comment]
I prepared a draft for this issue and introduced our project on the home page. I think I can edit or update when we need it.
Best.

**Comment by karacasoft** [comment]
I think we still need this thing open for a little more.
(There's no introduction in the home page? :V https://github.com/bounswe/bounswe2017group5/wiki )

**Comment by aycignl** [comment]
Yes, I am sorry! You're right.
Best.

**Comment by karacasoft** [comment]
Since project introduction in our home page is completed, I will close this issue for now...
