### ISSUE TITLE
www.interestr.com was registered before... :(

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#31]
www.interestr.com was registered by someone else 😞 

We might want to think about a new name. Let's gather all the name ideas here.

**Comment by Mccelik** [comment]
I have a suggestion, lets talk about it at the next meeting.

**Comment by karacasoft** [comment]
Mysterious idea... Why? :? There's no need for that. Please share what you have in your mind, so that we can elaborate on it. Or tell us your reasoning behind hiding your idea for a while. :D

**Comment by karacasoft** [comment]
The keywords we have taken in the meeting today:

* interest
* community
* network
* connection
* group
* activity
* content-sharing

**Comment by buzem** [comment]
okidoki can be interesting name

**Comment by iremUlutas** [comment]
interestr.io is available

**Comment by buzem** [comment]
OK , it is fine
