### ISSUE TITLE
Update Meeting Notes 5

### ISSUE THREAD

**Issue by aycignl** [bounswe/bounswe2017group5#32]
We need to add all of the action items to this note. 
There are more than three action items for that week.
Best.

**Comment by karacasoft** [comment]
We cannot!

We should've taken the notes of the action items. We cannot expect to remember who was responsible for the other actions correctly. Also, even if we add the action items for those actions, that doesn't mean anything. We have lost track of them anyways.

Let's be a little bit more careful about our meeting notes, shall we?

We can close this for now. But the missing action items can be added anyway. I'll leave the decision to you @aycignl .

**Comment by aycignl** [comment]
You are totally right. We should be more careful in these matters.
Now, I am closing this issue. 
Best.
