### ISSUE TITLE
specify our api project name

### ISSUE THREAD

**Issue by aycignl** [bounswe/bounswe2017group5#34]
Do you have any suggestions about the name of api project?
I think, it can be 'gaussianApi' which is a temporary name for api project.
What do you think of this name?

**Comment by karacasoft** [comment]
Well, our API doesn't really need a name, but our project does.
Check #31 pls. :D

We can also choose a temporary name for our project too. It'll help a lot when we want to talk about our project. But "Project Gauss" seems a little bit weird to me! :V

**Comment by buzem** [comment]
respect for gauss :)

**Comment by aycignl** [comment]
We used "gaussianApi" as the API project name.
