### ISSUE TITLE
API project needs to be done tomorrow!

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#35]
Now this is a real issue. :V

We have kinda decided what we will build. So here's my plan. Please confirm at some point in the future BUT not after tomorrow. 😀 

My plan:
- [x] Build a small base application.
- [x] Put it on github as the base project.
- [x] Everyone will pull the project, and start building the models we discussed.
  - [x] Profile Model
  - [x] Group Model
  - [x] Post Model
  - [x] Comment Model
  - [x] Tag Model
All models will be build with their serializers and views.
- [x] Add model relations
- [x] Set authentication and permissions.
- [ ] Write unit tests for each model (optional)

If you agree with me, please comment below and choose one of the tasks I've listed above. DO NOT mark them until they're completed.

**Comment by karacasoft** [comment]
The first two is already done by Gönül, so I've marked them here. I'll be working on the Profile Model that holds extra information for each user in system.

**Comment by iremUlutas** [comment]
I volunteer to implement the Group Model. Since this is a large one, those of you who want to contribute are always welcome.

**Comment by aycignl** [comment]
I can implement Comment Model.

**Comment by Morgazipa** [comment]
I would like to choose the Post Model.

**Comment by karacasoft** [comment]
Unit tests are not done for now. I'll check them out later. I thank you all for your support. Have a nice day.

I'll close this for now. But feel free to reopen whenever you feel like implementing the unit tests.
