### ISSUE TITLE
Requirements Review

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#53]
For the first time, we have seriously reviewed the requirements.
Here's the result:

In the definition of Post: 
Members do not send the post to their Profile Page. They send it to a group.

- [ ] 1112) Too General and Obvious (Not related with the system)
- [x] 1114) "they__ have__ created"
- [x] 11161) Duplicate of #1114
- [ ] 11171) No definition of "new activity"
- [ ] 11173) Do members see the members of other groups if the group is private? (Design choice)
- [x] 111(11)) Members should not be able to delete any post they want!!
- [ ] 111(12)) Do members really have to attach a comment to another comment? That may create some infinite loops of comments.
- [x] 1122) Wrong reference to 1113 (Might be 1114)
- [x] 1134) Completely unnecessary. Moderators might have too much power with this.
- [ ] 122) The news feed is created by the groups that the member has joined. Not by the tags of the groups.
- [ ] 123) This requirements is not testable!!
- [x] 1242) Was this really a requirement? lol
- [x] 1243) Said content should be defined as unwanted content
- [ ] 211) The term "Popular web browser" should be clarified. Web browser versions...
- [x] 213) In what next stages?
- [x] 232) Standard advertisement? Might be banner-ads

**Comment by aycignl** [comment]
I fixed the selected ones

**Comment by karacasoft** [comment]
We have completely renewed the requirements, so this has became irrelevant. Closing...
