### ISSUE TITLE
Use Cases Review

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#55]
We have also reviewed the Use Cases. Wow! That's a lot of work!
Results:

- [x] 1.Preconditions) So users cannot register from Phone Application/Tablet Application/Their own http client working on a microcontroller,...? Seems not fine!
- [x] 1.Description) "...some public groups...", which ones?
- [x] 1.Steps.2) 8-32 char__acters__
		   "The registration conditions.". What?

- [x] 5.Goal) Unregistered Users cannot join groups.!!
- [x] 5.Preconditions) Preconditions doesn't specify anything. This can be changed to be the same with the (1.Preconditions)

- [x] 6.Preconditions) "has authority" according to what?
- [x] 6.PostConditions) No ill-behaviour users? Wow. That's a lot of work.

**Comment by aycignl** [comment]
I think "has authority" is clear. Moderator is the admin of the system so it has some authorities such as to ban an unwanted user, to delete an unwanted post, and so on.

**Comment by karacasoft** [comment]
All fixed. Closing...
