### ISSUE TITLE
Create A personal Wiki Page

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group5#56]
Create a personal wiki page and link it to the right sidebar on wiki home.

**Comment by ThoAppelsin** [comment]
I have created a profile page to myself, added its link to the sidebar.

**Comment by smddzcy** [comment]
My page is also created (actually moved from my old group), thanks to @esra-aydemir 

Should we close it, if everyone is done?

**Comment by ThoAppelsin** [comment]
Orbay and Ramazan do not have one yet, or their links may also be broken.

**Comment by ThoAppelsin** [comment]
@norubai and @Morgazipa could you scribble something, it's not that so important, mine is almost completely irrelevant about the subject

**Comment by Morgazipa** [comment]
I actually have a personal page, but it seems that the link was broken for a long time. Hopefully, it is corrected now.

**Comment by karacasoft** [comment]
@norubai can you please create a wiki page for yourself? Just a simple page with name and e-mail will work fine for the time being.

**Comment by karacasoft** [comment]
A month is much more than required time for a simple wiki page. I have just created a filler page for you @norubai :|

With all pages created. This issue, (finally) can be closed.
