### ISSUE TITLE
Update Communication Plan

### ISSUE THREAD

**Issue by esra-aydemir** [bounswe/bounswe2017group5#59]
update communication plan for new members and meeting slots

**Comment by ThoAppelsin** [comment]
I have updated it, could somebody review it?

**Comment by karacasoft** [comment]
'Every necessary moment' might be a vague description. I don't think it's required to make it more descriptive, though. I just wanted to point it out.

Other than that, I see no other issues. :+1:

**Comment by esra-aydemir** [comment]
👍
