### ISSUE TITLE
Label the current issues

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#61]
We should label the current (and ideally all the previous, but it's too much work) issues after we create labels.

- Related issue: #60

**Comment by karacasoft** [comment]
You're talking about 8 issues that should be ~~tagged~~  labelled. Is it really too much? :V

**Comment by smddzcy** [comment]
@triforce930 You opened 8 issues in total in the previous semester? Wow 😄 Still, we can do that maybe in another issue.
@esra-aydemir Done, please review 🚀

**Comment by karacasoft** [comment]
I was counting the ones that are open right now. Are you planning to label the closed ones, too? If that's the case, yes, that's a lot of work!! 😄
