### ISSUE TITLE
Use case diagram needs to be updated

### ISSUE THREAD

**Issue by Morgazipa** [bounswe/bounswe2017group5#65]
Our current use case diagram doesn't reflect the recent changes to our requirements, such as the support for costumizable templates. Also we should perhaps move the use case diagram to the use case page in the wiki, because the diagram doesn't look very nice in an otherwise empty page. 

* Related Issues: #54 
* Other Related Links: [current use case diagram](https://github.com/bounswe/bounswe2017group5/blob/master/images/Use%20Case%20Diagram%20(7).png)

**Comment by karacasoft** [comment]
Was this completed? Or never even started?

**Comment by Morgazipa** [comment]
Although I updated the use case diagram to include new requirements,  I hesitated to close this issue because I was not very satistified with the result .  Afterwards I completely forgot about it.  Feel free to close it.

**Comment by karacasoft** [comment]
Is customizable templates added to the diagram? I could not check it.

**Comment by Morgazipa** [comment]
I now corrected the link to the image, it should be visible now.

**Comment by karacasoft** [comment]
Nice, the text font is hard to read (kind of), but looks cool. @smddzcy Should we accept this?

**Comment by Morgazipa** [comment]
This issue is open for a very long time. I have changed the font upon your request (@triforce930 ). Is it better right now?

**Comment by karacasoft** [comment]
lol. This issue has became the bane of your existence...

But the changes are pretty good! So it can be closed now. Thank you so much. :+1:
