### ISSUE TITLE
Choose a framework for the frontend

### ISSUE THREAD

**Issue by smddzcy** [bounswe/bounswe2017group5#70]
## About

* **Related Issues:** #67, #22 (mockup updates)
* **Other Related Links:** https://github.com/bounswe/bounswe2017group5/wiki/Mockup-web (web mockups)

We should choose a front-end framework to ease our development process. Some things we should consider while choosing:
- It shouldn't have a high entry barrier, which means it should be easy enough for the beginners to understand and be somewhat productive in ~2 weeks.
- It should be powerful enough to implement a dynamic UI as shown in our mockups.

### React
- 👍 Easy to learn
- 👍 Simple, modular, maintainable
- 👎 Not very powerful - although it's very powerful to build the view part, we'd require many other complementary libraries to build a whole web application
- 👍 Very popular

### Angular or Vue (they're very similar)
- 👎 Hard to learn
- ✊ Modular, but becomes very complex with time
- 👍 Extremely powerful, enough by itself
- ✊ Somewhat popular

### jQuery
- 👍 👍 Extremely easy to learn, one can learn in a couple days
- 👎 Simple, but not modular or maintainable
- 👎 Not powerful for anything, we'd require many complementary libraries for everything
- 👎 Not so popular anymore

### Ember
- 👎 👎 👍 👎 Hard to learn, very complex, powerful, not popular

### Other Candidates
- Any other framework that I couldn't remember
- Pure ES6 (not using any framework at all)
- Server-side rendering with Django templates (not having a dynamic UI, which I think would be terrible and too easy for the frontend team)

**Comment by smddzcy** [comment]
@bounswe/bounswe2017group5 I need everyone's input on this one. What do you think?

If we want to spend time on it but make it really good, my vote goes to React or Vue. (depending on everyone's knowledge)
If we want to make it easy, my vote goes to jQuery.

**Comment by karacasoft** [comment]
If at least one person wants to dedicate himself on this job, I think React is possible. If no one wants to be the victim, jQuery seems to be the way. 
<sub>I actually don't want use the term 'victim' here, because frontend people do really cool stuff that I probably will never be able to do. :V</sub>

Thanks for the pros/cons list btw. that really helps those non-web oriented people like me :+1:

**Comment by ThoAppelsin** [comment]
I know nothing about any of the frameworks for JS. Pure JS has always worked well on me. I cannot really comment on the others.

**Comment by esra-aydemir** [comment]
Since we will work on them as a team, I think "Extremely easy to learn" wins. They both have pros/cons so they all will cause problems somehow. I hope it is also "Extremely easy to learn the answers of issues".

jQuery

**Comment by yfenes** [comment]
Esra +1

**Comment by murat0431** [comment]
Esraa +1

**Comment by ThoAppelsin** [comment]
Although I have never used it, I have seen jQuery in use several times in the past years, and I have grown some sort of antipathy within me against the jQuery. This is no reason to not use it, but I wanted to say it sooner than later.

As far as I know, it is not that so extremely easy to learn, either. For example, it assumes that you have a decent amount of knowledge on CSS Selectors, unless you don't want to use it to it's entirety.

I would say that jQuery is rather "easy to type", but I'm not sure if it's that so **extremely** easy to learn, really.

**Comment by karacasoft** [comment]
> Since we will work on them as a team

I strongly disagree that this should be the reason why we should go with the easy solution. We will NOT work on small parts of the project all together. 

We might want to have a group of people working on learning a frontend framework and create re-usable, testable(is that a word?) components, rather than having everybody patch the frontend stuff as we go through the project.

**Comment by smddzcy** [comment]
@ThoAppelsin Assuming you know the basic concepts of JS (e.g. callbacks, closures) and CSS selectors, you can learn jQuery **in 1 day**. It's the easiest _framework_, because actually it's not a framework, it's a huge library that does everything in an unstructured manner (like PHP). After learning the basic syntax and way of doing things with it (1 day), there is not much to learn, you can only memorize the methods.

Then it's jQuery. Here are some docs to get you started, for those of you who know some kind of JS but no jQuery:
- JS Callbacks & Closures (we'll use these a lot in jQuery): https://stackoverflow.com/questions/2070275/what-are-closures-and-callbacks
- jQuery Getting Started: https://www.w3schools.com/jquery/jquery_get_started.asp
- jQuery UI (a famous UI library for jQuery, we should use it): https://learn.jquery.com/jquery-ui/getting-started/
- SPA (Single Page Application) with Handlebars & jQuery: https://tutorialzine.com/2015/02/single-page-app-without-a-framework
  - We can discuss this one. We don't have to create a SPA, but otherwise it'd be easy and not so _cool_.

**Comment by smddzcy** [comment]
@triforce930 By the way, choosing jQuery means that we won't use the views generated by Django and make an API-only backend (no server-side rendering). What do you think about this? 😄

**Comment by karacasoft** [comment]
@smddzcy Nope that might not be the case. I have used Django and jQuery with server-side rendering before. I think that's the case that is more likely to happen when we use a framework. 😄  

Though we will use jQuery anyway, if no one comes out and says that she'll learn Angular/React/something else. We might have to set a timeout for this conversation though. It'll go on forever, if we leave it up.

**Comment by smddzcy** [comment]
@triforce930 Alright, server-side rendering with jQuery then 👍 Closing the issue 😄
