### ISSUE TITLE
Django has no non-relational database support

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#73]
## About

* **Other Related Links:** https://django-mongodb-engine.readthedocs.io/en/latest/topics/setup.html

Django mongo-db engine relies on a fork of Django project (django-nonrel) which is a fork of the original Django project with non-relational database support. Is this ok? I personally think this may become a mess, later.

**Comment by smddzcy** [comment]
Let's use Postgres, we can use json data types.

**Comment by karacasoft** [comment]
Perfect,
Django has postgres support internally. Case closed...
