### ISSUE TITLE
Token Authentication on Backend should be finished

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#79]
## About

* **Related Issues:** #78  

Token Authentication should be working for registered users on the API.

- [ ] Write token authentication view for API.
- [ ] Write tests to validate that token authentication is working and its return format is correct.

**Comment by smddzcy** [comment]
@triforce930 `status: review`? I can't see the PR, is this done?

**Comment by karacasoft** [comment]
It was not reviewed for a long time, so I used my _super administrative powers_ and merged the PR by myself.

This can be closed.
