### ISSUE TITLE
Groups Model: the beginning

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#80]
## About

* **Related Issues:** #78 

We should start building a model for Groups. For this job to be considered 'finished' the Group model shall have these attributes:
* Create / Update / Delete
* Should let users join the group
* Should let users leave the group
* Its endpoints shall be set under /api/v1/groups

## To-do

- [x] Finish Group Model.
- [x] Write tests to validate that the Group model works.

**Comment by smddzcy** [comment]
@norubai Any progress?

**Comment by oal55** [comment]
Yeah It seems to be done and working.

**Comment by karacasoft** [comment]
Do **not** directly push to the main branches. Branch out from an existing branch and push to that branch instead. We should be able to review your changes, and request changes if we need. For this time I'll consider this completed.
