### ISSUE TITLE
Data Template model

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#81]
## About

* **Related Issues:** #78 

We should start building the Data Template model. We already have a draft for this model. It has to have these attributes to be considered 'finished':
* Should have an interface to add/remove fields from its objects.
* Should expose an endpoint through the `api` project, under the url `/api/v1/templates`

## To-do

- [ ] Finish the Data Template model.
- [ ] Write tests to validate that it works.

**Comment by smddzcy** [comment]
@ThoAppelsin Any progress?
