### ISSUE TITLE
We shall have a working Post model

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#82]
## About

* **Related Issues:** #78 

A template for the Post model already exists. But should have its fields filled and should expose an endpoint via `/api/v1/posts`. Only requirement for this to be done is to make Posts expose an endpoint. Other than that, adding some fields to the Post model is highly appreciated.

## To-do

- [ ] Make Post model usable.
- [ ] Write tests to validate that it is indeed usable.

**Comment by smddzcy** [comment]
@iremUlutas Any progress?
