### ISSUE TITLE
Frontend Pages; must have some drafts to work with...

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#83]
## About

* **Related Issues:** #78 

We at least have to finish 5/6 pages until the milestone. We need some people working on these. Basic requirement is to make it look as closer to the mockups as possible. Other than that, we have 5 pages to be finished

- [x] Homepage
- [x] Login/Register Pages (we could combine these into one)
- [x] Create a Group Page
- [x] Groups Page
- [x] Group Detail Page

**Comment by smddzcy** [comment]
I'M ON IT 🐱

**Comment by smddzcy** [comment]
@triforce930 What is `Groups Page`, exactly which mockup? I'll finish the rest tomorrow (hopefully).

**Comment by karacasoft** [comment]
Well, there's no groups page. We designed our mock-ups to have the groups listed on the right of the news feed. We'll have to build one for the next milestone, though. You may create one without a strict style requirement.

**Comment by smddzcy** [comment]
@triforce930 Check the PR, everything is done 👌

**Comment by karacasoft** [comment]
Review completed. Closing...
