### ISSUE TITLE
Postgresql setup in the setup script does not work very well

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#85]
## About

The script could not create a user and database in my computer. We might need a more sophisticated solution for this, or give information about how to setup the postgresql, so that people can work locally on their computer.

## Visuals

![image](https://user-images.githubusercontent.com/5247569/31913640-6bbef6d8-b850-11e7-8b80-2ba50afe437b.png)

**Comment by karacasoft** [comment]
Until I get something ready for this, please reach out to me if you require setting up postgresql.

**Comment by smddzcy** [comment]
role "karacasoft"? Hmm... 🤔

**Comment by karacasoft** [comment]
Yeah, it uses the username I have on this computer and it does not identify me as the database user.

**Comment by murat0431** [comment]
Yeah we should set the postresql manually. I should read here instead of using setup.sh :(

**Comment by karacasoft** [comment]
https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04

This guide is pretty good. Follow after "Create a Database and Database User" title. Set username to bounswe2017group5 and set password 1234. 

After doing all of this, run this command too, to make the tests work:

`ALTER USER bounswe2017group5 CREATEDB;`

**Comment by smddzcy** [comment]
I agree that it's a very opinionated script 😅 You should be running a UNIX-based system with Postgres installed and the basic `postgres` user already set up, otherwise it'll fail.

**Comment by karacasoft** [comment]
@smddzcy and I will help people who cannot setup postgresql for their local environment. You may let me know whenever you need help about this. Case closed...
