### ISSUE TITLE
Research about wikidata queries

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#88]
## About

* **Related Issues:** #75 

We have to research wikidata queries, learn about how to use them for semantic tagging in our project.

### Task requirements
* Research wikidata, learn how we can get item information
* Prepare a very small document about how to use wikidata queries, and what is useful for our project
* Publish the document on Slack

This task has 6 hours of volunteer time. After the timeout, the task will be assigned to a random person in the group.

**Comment by Morgazipa** [comment]
I would like to help.

**Comment by karacasoft** [comment]
All right, task assigned to you then :+1: Here's a good starting point:
https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/Wikidata_Query_Help

**Comment by Morgazipa** [comment]
[wikidata.txt](https://github.com/bounswe/bounswe2017group5/files/1435862/wikidata.txt)
Here you can find the report.
