### ISSUE TITLE
Interestr logo missing on homepage.html

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#89]
## About

We should put the interestr logo on the front page. The logo can be redesigned in the process.

### Requirements
* Design a logo for the project
* Put the logo on the page, index.html

Volunteer timeout: 4 hours

**Comment by smddzcy** [comment]
I can do the design 🎨

**Comment by smddzcy** [comment]
Designed 3 logos, we should pick one:

### 1
`I` can be used as the small logo
![logo](https://user-images.githubusercontent.com/13895224/32021342-ce4924ae-b9db-11e7-9e82-bc1ccf40ff1d.png)

### 2
![logo2](https://user-images.githubusercontent.com/13895224/32021778-12bf0058-b9dd-11e7-8b4f-4b9fd88c9f0e.png)

### 3
`I` part is the small logo
![logo3](https://user-images.githubusercontent.com/13895224/32021780-12f2fd18-b9dd-11e7-943b-6f9f72034ab5.png)

---

My vote goes to **1**.

**Comment by smddzcy** [comment]
@triforce930 Probably no one will look here and contribute to our discussion, so I use my _super voting power_ as the designer and pick the logo 1 immediately 🚀  Created the PR, please review.

**Comment by karacasoft** [comment]
> ...as the designer...

We have accidentally made you a designer lol
I think logo 1 is the best here, too. Other ones are just hard to read. Not simple enough, in other words. But I'll do the review tomorrow with a fresh mind.

**Comment by smddzcy** [comment]
We can close this one, there is only a small fix left on the PR and we've designed the logo already 👨‍🎨
