### ISSUE TITLE
install pillow

### ISSUE THREAD

**Issue by oal55** [bounswe/bounswe2017group5#94]
## Pillow

Migrate.py printed out something along the lines 'you need to download pillow if you want to support image fields.' and I didn't question its integrity. Now we support image fields.

After you activate your environment, you can install pillow with
``` pip install pillow```

**Comment by karacasoft** [comment]
True, image fields required that stuff. Completely forgot it. We can add it to the installation documentation

**Comment by karacasoft** [comment]
It seems that you have also installed another dependency named django_extensions. You should have let us know about this. :| I have added it to the requirements.txt for the time being.

**Comment by karacasoft** [comment]
Requirements can be installed via requirements.txt file in the api directory.

`pip install -r requirements.txt`

We no longer need to keep track of requirements
