### ISSUE TITLE
Group management view needs to be rewritten using django-rest-framework

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#96]
## About

* **Other Related Links:** 
* https://github.com/bounswe/bounswe2017group5/commit/2287f1e4812db4c6fdc31c1bb3f5866bca66938d#diff-a224ae36892ad9b8a65a454b5c43cbf0

The view in the given file is not written using django-rest-framework APIViews. This has to be completely rewritten using django-rest-framework later. Please check out: http://www.django-rest-framework.org/api-guide/routers/

**Comment by oal55** [comment]
I'll get on it

**Comment by oal55** [comment]
@smddzcy , @triforce930  Am I closing this :O ?

**Comment by smddzcy** [comment]
@norubai Sure, if it's fixed 🤓
