### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#97]
## About

This is something we have to consider at some point. 

Check this out, and let me know what you all think: 
http://www.django-rest-framework.org/topics/documenting-your-api/

**Comment by smddzcy** [comment]
We should document each method as we implement otherwise it'll be too hard later on. The easiest way to achieve this: **Not accepting PRs that has undocumented - untested code**.

**Comment by karacasoft** [comment]
With #109, there's no need for this to left open, I guess...
