### ISSUE TITLE
One of the tests written for Posts fails for no reason

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#98]
## About

* **Related Issues:** #91 

When I run the tests the test named `test_existing_post` fails. But I can see that posts return fine when I run the API itself.

**Comment by oal55** [comment]
The asserted JSON is missing its data_template field. I think it was implemented after the test case was written.

**Comment by karacasoft** [comment]
Yup, that's the reason. It's probably the best if we just test specific fields like the post's owner or the content of the post. Not the whole content of the response

**Comment by iremUlutas** [comment]
totally agree. working on it.

**Comment by smddzcy** [comment]
@iremUlutas Is this still failing?

**Comment by oal55** [comment]
As of the last merge @Morgazipa did, we don't have any failing tests in master branch. So maybe we shall close this as well. @smddzcy
