### ISSUE TITLE
The first version Groups Page

### ISSUE THREAD

**Issue by karacasoft** [bounswe/bounswe2017group5#99]
## About

We shall start integrating frontend with backend, at some point in the very near future. This task includes designing a groups page:
* Only authorized(logged in) users shall be able to enter the page.
* The page shall list the groups that are in the system.
* The page should also have a link to "create a group" page.

**Comment by murat0431** [comment]
Actually i created a new branch(templates). I will first change dummy variables with the real ones.After that i might need some help about authentication process. Also our template.html has login and signup link in the navigation bar.How can we use this as a base.html? I guess we should change it little bit.

**Comment by karacasoft** [comment]
>  i might need some help about authentication process

Authentication process is someone else's job. You may want to use this if you want to let only the authorized users in: https://docs.djangoproject.com/en/1.11/topics/auth/default/#the-login-required-decorator

> Also our template.html has login and signup link in the navigation bar.How can we use this as a base.html?

Yes, we may want to remove those links when a user logs in. There are multiple ways to do this. You can fix that, or leave it there. We can resolve the issues once I get to review your changes.

**Comment by murat0431** [comment]
Okay let me read this link. When do you want me to push this page. Today i am extremely busy. Is tomorrow evening alright? I will send the page so that you can review it. After your review i can fix the bugs.

**Comment by karacasoft** [comment]
> When do you want me to push this page

As soon as possible :smile:

**Comment by murat0431** [comment]
@triforce930 how can i learn number of groups that has been created? I need it to create a for loop

**Comment by smddzcy** [comment]
@murat0431 
> Also our template.html has login and signup link in the navigation bar.How can we use this as a base.html? I guess we should change it little bit.

You can split our template into 3 parts; `base.html`, `navbar_guest.html` and `navbar_user.html` (this you can find in some page like `groups.html`). Then, we can have 2 base pages; `base_guest.html` and `base_user.html`, with the correct navbar and other potential user/guest specific things.
